### PR TITLE
#8 Pages: HeadMates Listing Page for the System Map

### LINKED ISSUE #8: Pages: HeadMates Listing Page
This issue is required to complete #7 for the System Map

> *this is taken from the grand pdf [page 41](https://drive.google.com/file/d/1JGqPSo2Lem2A_XrcSU9h19yzHA19k7Ba/view?usp=sharing)*

The System Map profile that is accessed after the basic profile input has additional traits and information that can then be added.

The basic name, gender, age, and profile pic are added, then that appears on the System Map as a clickable button that leads to the associated profile

image

### PR DESCRIPTION
**Pull request by wendyyng**
# What
This pull request resolves #8 . It adds the SystemMapListingPage and SystemMapProfileCard components that show the Headmates' information. The SystemMapListingPage is imported into the AppRouter's system-map path.

# Covers
- #8  
- #7 

# To be reviewed
- Naming of the Listing Page and Profile Card
- The path for the Listing Page
- The parameter of useUserScopedCollectionData needs to updated with correct collectionPath: demo data is currently used for displaying the data on the Profile Card
- Styling and responsiveness of the Profile Cards

## Screenshots

screencapture-localhost-3000-system-map-2022-11-21-17_46_55

screencapture-localhost-3000-system-map-2022-11-21-17_47_18

screencapture-localhost-3000-system-map-2022-11-21-17_46_32

### CODE REVIEW

**Comment by wendyyng** [comment]
Updates:
- Corrected the font styles of gender and age on the Profile Card
- Capitalize gender using built in JavaScript methods

screencapture-localhost-3000-system-map-2022-11-21-18_44_08

**Review by ryanolee — APPROVED** [review]

**Comment by ryanolee** [comment]
Hi @wendyyng , 
Tested this locally and this looks really good. I have updated the emulator data locally so that it matches with the demo data added in the PR and re-exported it to VCS. Would you be free it give this a once over and confirm the commit I just added did not break anything. If so will get this merged! Thanks for looking at this 🙌

**Comment by wendyyng** [comment]
> Hi @wendyyng , Tested this locally and this looks really good. I have updated the emulator data locally so that it matches with the demo data added in the PR and re-exported it to VCS. Would you be free it give this a once over and confirm the commit I just added did not break anything. If so will get this merged! Thanks for looking at this 🙌

@ryanolee Thank you so much for reviewing! And I made a few updates:
- The emulator data do not include 'id', so I used index when mapping - probably not optimal and we might need to modify the emulator data, but for now console stops showing the error message
- The emulator data also do not have profile picture URL
- Add propType 'id' in SystemMapProfileCard - it didn't show any errors before, but I added it for the consistency
- I added a helper file with a function for capitalizing text and used it to capitalize gender in profile card
- Fix formatting with prettier using npx

**Comment by wendyyng** [comment]
MBO_Bug
Not related to this issue but I think there's a bug in Navbar that causes this error. Either removing edge altogether or changing edge='false' would stop the error from showing without changing the UI. We might need to open another issue for this.

```
<IconButton
    color="inherit"
    aria-label="open drawer"
    onClick={!open ? handleDrawerOpen : handleDrawerClose}
    edge="center"
  >
    {open ? <CloseIcon /> : <MenuIcon />}
  </IconButton>
```

**Comment by wendyyng** [comment]
The last commit removed the helper to capitalize text and used MUI's textTransform instead.

**Review by ryanolee — APPROVED** [review]

**Comment by ryanolee** [comment]
Looks great to me! We can probably fix forwards with the other warning. Thanks for the contribution @wendyyng !

**Pull request merged**
